name: Build
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v1
      id: auth
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        token_format: access_token
    - uses: docker/login-action@v2
      with:
        registry: asia-southeast1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: docker/setup-buildx-action@v2
      with:
        version: latest
    - uses: docker/build-push-action@v4
      with:
        provenance: false
        push: true
        tags: |
          asia-southeast1-docker.pkg.dev/deploys-app/public/log:${{ github.sha }}
          ${{ secrets.REGISTRY }}/deploys-app/log:${{ github.sha }}
